<p><strong>Driver Terms &amp; Conditions of Service</strong></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<p><strong>1 ABOUT POUND CABS LTD TERMS AND CONDITIONS</strong></p>
<p><span style="font-weight: 400;">1.1 In these terms and conditions, as they may be amended from time to time ( &ldquo;Terms &amp; Conditions&rdquo; ) references to &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo; and any similar expression shall include the Company and (to the extent required where these terms are incorporated by reference in any other agreement) any subsidiary of the Company. Unless the context otherwise requires, words denoting the singular shall include the plural and vice versa, words denoting any gender shall include all genders and words denoting persons shall include bodies corporate and unincorporated, associations, partnerships and individuals. </span></p>
<p><span style="font-weight: 400;">1.2 These Terms &amp; Conditions are entered into between us (&ldquo;Pound Cabs Ltd&rdquo;) and the customer (&ldquo;you&rdquo;). &nbsp;("Business") is refers to any business entity entering into a contract with Pound Cabs Ltd for the installation of the PDA or use of its service in any other manner. </span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<p><strong>2 INFORMATION ABOUT POUND CABS LTD AND THE USE OF ITS SERVICE &nbsp;</strong></p>
<p><span style="font-weight: 400;">2.1 Pound Cabs Ltd is a marketing platform between businesses (taxi companies/private hire firms) and users (passengers) linking the two together allowing users to access transport via Pound Cabs Ltd's affiliated businesses. Pound Cabs Ltd's company number is 09403318, registered at HQ Hamill, Clippers Quay, Salford Quays, M50 3XP, UK.</span></p>
<p><span style="font-weight: 400;">2.2 The registration and signup process for the business is free. &nbsp;Pound Cab reserves the right to levy cancellation charges set out in clause 4.1 &nbsp;</span></p>
<p><span style="font-weight: 400;">2.3 Pound Cabs Ltd will install Personal Digital Assistant (PDA) into each vehicle which enters into a contract with Pound Cabs Ltd. </span></p>
<p><span style="font-weight: 400;">2.4 When a passenger books a cab via the Pound Cab Ltd APP the driver (you) will be able to see the closest job and be able to accept the job by clicking &ldquo;yes&rdquo; on the PDA. &nbsp;</span></p>
<p><span style="font-weight: 400;">2.5 The passengers can pay the full fare to the driver (you) in cash or pay Pound Cabs Ltd direct via Pound Cabs Ltd's APP. </span></p>
<p><span style="font-weight: 400;">2.4 If the customers pay via Pound Cabs Ltd's APP, then we, Pound Cabs Ltd, will pay the drivers (you) based on our pre agreed terms when drivers sign up with us (Pound Cabs Ltd).</span></p>
<p><span style="font-weight: 400;">2,5 Our email is info@poundcabs.co.uk, (&ldquo;Pound Cabs Ltd&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; and &ldquo;our&rdquo;) For further details about Pound Cabs Ltd please visit our website; http://www.poundcabs.co.uk/ For information on how we will process your personal data, please see our Privacy Policy (Separate Document) </span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<p><strong>3 YOUR USE OF POUND CABS LTD'S SERVICES</strong></p>
<p><span style="font-weight: 400;">3.1 You can only use the Pound Cabs Ltd services (which include the Pound Cabs APP) if you have successfully completed your registration with us and that registration remains valid. Your registration remains at our discretion at all times. You will be deemed to have accepted these terms and conditions (&ldquo;Terms&rdquo;) when you register with us and whenever you use any of such Pound Cabs Ltd services.</span></p>
<p><span style="font-weight: 400;">3.2 By accessing and using the Website you the user</span> <span style="font-weight: 400;">("you") are agreeing to be bound by these terms and conditions (the "Terms") which govern your access to and use of the Website.</span></p>
<p><span style="font-weight: 400;">3.3 Access to the site is permitted on a temporary basis and the Pound Cabs Ltd reserves the right to withdraw or amend the services provided on the site without notice. Pound Cabs Ltd will not be liable if for any reason the site is unavailable at any time or for any period.</span></p>
<p><span style="font-weight: 400;">3.4 Pound Cabs Ltd may restrict access to users to some parts of the site or to the entire site for technical, administrative or legal reasons.</span></p>
<p><span style="font-weight: 400;">3.5 If you choose, or you are provided with, a user identification code, password or any other piece of information as part of the Pound Cabs Ltd's security procedures, you must treat such information as confidential and you must not disclose it to any third party. Pound Cabs Ltd has the right to disable any identification code or password whether chosen by you or allocated by the Pound Cabs Ltd at any time if in the Pound Cabs Ltd's opinion you have failed to comply with any of the provisions of these terms of use.</span></p>
<p><span style="font-weight: 400;">3.6 You are responsible for making all arrangements necessary for you to have access to the site. You are also responsible for ensuring that all persons who access the site through your internet connection are aware of these terms and that they comply with them.</span></p>
<p><span style="font-weight: 400;">3.7 You may use the site or APP only for lawful purposes. You must not use the site:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">In any way that breaches any applicable local, national or international law or regulation.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">In any way that is unlawful or fraudulent or has any unlawful or fraudulent purpose or effect.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">For the purpose of harming or attempting to harm minors in any way.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To send, knowingly receive, upload, download, use or re-use any material that does not comply with Content Standards.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To transmit or procure the sending of any unsolicited or unauthorised advertising or promotional material or any other form of similar solicitation (spam).</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To knowingly transmit any data, send or upload any material that contains viruses or any other computer code, programs or files designed to destroy, interrupt or limit the functionality of any computer, computer software or hardware or telecommunications equipment.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To provide false, inaccurate data. You can update or correct your details at any time via the Pound Cabs Ltd APP.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To do anything which we reasonably believe to be disreputable or capable of damaging our reputation.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To be in breach of confidence or privacy or of any third party&rsquo;s rights including copyright, trade mark or other intellectual property rights; (iii) is posted, shared or transmitted for the purpose of advertising or promoting yourself or any third party; or (iv) is misleading or misrepresentative as to your identity or which in any way suggests that you are sponsored, affiliated or connected with Pound Cabs Ltd. </span></li>
</ul>
<p><span style="font-weight: 400;">3.8 The use of Pound Cabs Ltd services grants you no rights in relation to our intellectual property rights (including, without limitation, copyright, trade marks, logos, graphics, photographs, animations, videos and text or rights in and to Pound Cabs Ltd's software, applications and website) or the intellectual property of our retail or advertising partners, other than the non&shy;transferable, personal right to use and receive the Pound Cabs Ltd services in accordance with Pound Cabs Ltd's Terms.</span></p>
<p><span style="font-weight: 400;">3.9 and warrant that when using any Pound Cabs Ltd services: you have all the appropriate licenses, approvals and authority to provide taxi services to passengers; that you own or have the legal right to operate the vehicle you use and that such vehicle meets all relevant safety standards and regulatory requirements and laws; and that you have valid insurance cover for your vehicle and services.</span></p>
<p><span style="font-weight: 400;">3.10 and acknowledge that we have limited control over the nature and content of information and chat transmitted or received by you or other users of any Pound Cabs Ltd services. Although we reserve the right to do so, we do not monitor such content in the usual course of business and will not be liable for any such content. If you have a complaint about another user please contact us via the Pound Cabs Ltd APP or through our website; http://www.poundcabs.co.uk/</span></p>
<p><span style="font-weight: 400;">3.11 to compensate and defend us fully against any claims or legal proceedings brought against us by any other person as a result of your breach of these Terms.</span></p>
<p><span style="font-weight: 400;">3.12 that you will comply with all applicable laws and requirements in force from time to time and be ultimately responsible for the provision of your taxi services to passengers (including without limitation, following safety laws in for the use of mobile devices while driving).</span></p>
<p><span style="font-weight: 400;">3.13 In relation to the reporting information that we provide, we use all reasonable endeavours to ensure that such information is reasonably accurate but we cannot provide guarantee that it will always be correct or accurate You should use your own judgment when acting on the basis of information provided.</span></p>
<p><span style="font-weight: 400;">3.14 Pound Cabs Ltd APP is a Pound Cabs Ltd service to arrange payments from passengers. </span></p>
<p><span style="font-weight: 400;">3.15 Pound Cabs Ltd are not responsible for the behaviour, actions or inactions of passengers whether or not they are Pound Cabs Ltd customers (although, where such passenger is a Pound Cabs Ltd customer who has ordered your taxi using the Pound Cabs Ltd APP , payment protection is provided in certain circumstances. Any contract for the provision of taxi services is between you and the passenger and not Pound Cabs Ltd. &nbsp;Pound Cabs Ltd simply provide a portal to introduce drivers and passengers and/or facilitate payments in certain circumstances.</span></p>
<p><strong>4 PAYMENT AND CHARGES</strong></p>
<p><span style="font-weight: 400;">4.1 You can register for Pound Cabs Ltd's services for free and can generally use the Pound Cabs Ltd APP.</span></p>
<p><span style="font-weight: 400;">For business users we will provide</span> <span style="font-weight: 400;">free installation for all vehicles provided by Pound Cabs Ltd. &nbsp;Any cancellation within 12 months of sign up between (Pound Cabs Ltd &amp; "Business" in question) will be subject to a &pound;2500 charge (applied to the business/individual).</span></p>
<p><span style="font-weight: 400;">4.2 Pound Cabs Ltd's Charges for use of Pound Cabs Ltd APP are set out on the Pound Cabs Ltd APP and website (provided you are a registered user) and you will also be charged any processing fee charged by the relevant payment provider and/or any other commission or service charge or cost that Pound Cabs Ltd's incurs</span><strong>. </strong><span style="font-weight: 400;">Pound Cabs Ltd does not provide any payment protection or guarantees in relation to Pound Cabs Ltd APP&rsquo;s transactions irrespective of whether or not the passenger has booked the taxi via the Pound Cabs Ltd APP. </span></p>
<p><span style="font-weight: 400;">4.3 You will be responsible in event that a payment proves to be fraudulent or unauthorised or if the payment from the customer fails to be processed for any other reason. The following additional terms apply where you use &nbsp;&nbsp;Pound Cabs Ltd APP.</span></p>
<p><span style="font-weight: 400;">4.4 you may only accept and process payments using Pound Cabs Ltd's APP where the passenger has completed the transaction.</span></p>
<p><span style="font-weight: 400;">4.5 If Pound Cabs Ltd owes you any fees we shall pay less: (i) any fees and/or other monies you owe to Pound Cabs Ltd and/or any chargeback costs (where card issuers, or financial institutions refuse to settle a transaction or demand payment in respect of a disputed transaction and the administrative costs incurred as a result of this); and (ii) any fees or costs or expenses in connection with assessments which card schemes or other financial institutions require us or you to pay.</span></p>
<p><span style="font-weight: 400;">4.6 Pound Cabs Ltd has the right to suspend the processing of any transaction where Pound Cabs Ltd reasonably believes that the transaction may be fraudulent or involves any criminal activities or where Pound Cabs Ltd reasonably believes you to be in breach of these Terms.</span></p>
<p><span style="font-weight: 400;">4.7 The charges are set out on the APP and website (provided you are a registered user) and you will also be charged any processing fee charged by the relevant payment provider and/or any other commission or service charge or cost that Pound Cabs Ltd incurs. Where Pound Cabs Ltd registered passengers pay with a card through the Pound Cabs Ltd APP, Pound Cabs Ltd will provide payment protection over such transactions although no such payment protection is provided if the passenger pays using Pound Cabs Ltd regardless of whether or not the passenger has booked the taxi via the Pound Cabs Ltd APP. The following additional terms apply to Pound Cabs Ltd transactions:</span></p>
<p><span style="font-weight: 400;">4.8 Pound Cabs Ltd may suspend transaction where Pound Cabs Ltd's reasonably believes that the transaction may be fraudulent or involves any criminal activity or where Pound Cabs Ltd reasonably believes you to be in breach of these terms; and</span></p>
<p><span style="font-weight: 400;">4.9 any fees due to you shall be paid by Pound Cabs Ltd less: (i) any fees and/or other amounts you owe to Pound Cabs Ltd and/or any chargebacks and chargeback costs where a passenger disputes the services you provided; and (ii) any fees or costs or expenses in connection with assessments which card schemes or other financial institutions require us or you to pay. You agree to co&shy;operate with Pound Cabs Ltd (including through the provision of relevant information) in the event of a dispute over any transaction.</span></p>
<p><span style="font-weight: 400;">4.10 In accordance with our Terms and Conditions set out in the APP and website the balance of any payments owing to you from passengers will be provided. &nbsp;Pound Cabs Ltd may withhold or delay payments to you where:</span></p>
<p><span style="font-weight: 400;">4.11 The transaction is considered to be fraudulent/suspicious or where a payment requires approval/authorisation with a card issuer.</span></p>
<p><span style="font-weight: 400;">4.12 Pound Cabs Ltd has reasonable grounds to suspect that the passenger did not authorise the relevant transaction or the passenger disputes authorisation. </span></p>
<p><span style="font-weight: 400;">4.13 You accept that payment providers may ask that Pound Cabs Ltd or they conduct an audit of your activities and/or of your records and accounts to ensure compliance with these Terms and use of the Pound Cabs Ltd services including Pound Cabs Ltd APP and you agree to co&shy;operate fully with any such audit. You also agree that you will co&shy;operate in relation to any financial crime detection that is required and to assist Pound Cabs Ltd in complying with any laws and card or financial institution rules or policies.</span></p>
<ol start="5">
<li><strong> TERMINATION</strong></li>
</ol>
<p><span style="font-weight: 400;">5.1 We may terminate these Terms and close any account you have with us by giving you 7 days' notice in writing by email to your registered email address. We may also terminate these Terms and close your account without notice if you breach any of your obligations under these Terms, if you cease to be a licensed taxi driver, if bankruptcy proceedings are brought against you or if you do not pay a court judgement on time.</span></p>
<p><span style="font-weight: 400;">5.2 We reserve the right to suspend, restrict or terminate your access to Pound Cabs Ltd at any time without notice if we have reasonable grounds to believe you have breached any of these Terms. This shall not limit our right to take any other action against you that we consider appropriate to defend our rights or those of any other person.</span></p>
<p><span style="font-weight: 400;">5.3 You may cancel these Terms at any time by simply closing your account by following the instructions on the APP or website.</span></p>
<ol start="6">
<li><strong> POUND CAB'S LEGAL OBLIGATIONS AND LIMITS ON LIABILITY</strong></li>
</ol>
<p><span style="font-weight: 400;">6.1 Pound Cabs Ltd accepts liability for death or personal injury caused by our negligence or that of our employees and agents. We do not seek to exclude liability for fraudulent misrepresentation by us or our employees or agents. You have certain rights under the law. These include that we will provide Pound Cabs Ltd to a reasonable standard and within a reasonable time. Your statutory rights remain unaffected. For more information about your statutory rights you can contact your local Citizens Advice Bureau, Trading Standards Office or consult a legal representative.</span></p>
<ol start="7">
<li><strong> LIMITS ON LIABILITY </strong></li>
</ol>
<p><span style="font-weight: 400;">7.1 If Pound Cabs Ltd is in breach of these Terms, We shall only be liable for losses which are a reasonably foreseeable consequence of such a breach, up to a maximum of &pound;1,000. "Foreseeable" means that the losses could have been reasonably contemplated by you and us at the time of entering into these Terms.</span></p>
<p><span style="font-weight: 400;">7.2 Pound Cabs Ltd is not responsible for: (i) losses not caused by our breach; (ii) the actions or inactions of any passengers (other than in the circumstances set out in clause 2.2); (iii) the actions or inactions of other drivers; (iv) indirect losses which means loss to you which is a side effect of the main loss or damage and where you and us could not have reasonably anticipated that type of loss arising at the time of entering into these Terms; or (v) failure to provide Taxi-e Ltd or to meet any of our obligations under these Terms where such failure is due to events beyond our control (for example a network failure).</span></p>
<ol start="8">
<li><strong> COMPETITIONS RULES</strong></li>
</ol>
<p><span style="font-weight: 400;">8.1 Pound Cabs Ltd requires you to refer to its full Competition Rules page before entering into any Pound Cabs Ltd competition. Pound Cabs Ltd posts the details of all competitions on Pound Cabs Ltd's web site where the closing date is specified. To enter any Pound Cabs Ltd competition you must be: (a) united kingdom resident; and (b) 18 years old or over at the time of entry. No purchases are necessary. Any employees or members of immediate family of Pound Cabs Ltd are restricted from entering any Competitions. </span></p>
<ol start="9">
<li><strong> SUBCONTRACTING, SERVICE LEVELS &amp; DISPUTE RESOLUTION</strong></li>
</ol>
<p><span style="font-weight: 400;">9.1 Pound Cabs Ltd may wish to transfer its rights or obligations or sub-contract its obligations under these Terms to another legal entity. You agree that Pound Cabs Ltd may do so provided that this will not adversely affect the standard of service you receive under these Terms. As set out in clause 5.3, you may terminate your agreement with Pound Cabs Ltd at any time. These Terms are personal to you. You may not transfer your rights or obligations under these Terms to anyone else.</span></p>
<p><span style="font-weight: 400;">9.2 If you are in breach of Pound Cabs Ltd's Terms and Pound Cabs Ltd takes no action against you, Pound Cabs Ltd will still be entitled to its rights and remedies in any other situation where you breach these Terms.</span></p>
<p><span style="font-weight: 400;">9.3 If any part of these Terms is disallowed or found to be ineffective by any court or regulator, the other provisions shall continue to apply.</span></p>
<p><span style="font-weight: 400;">9.4 These Terms are not intended to give rights to anyone except you and Pound Cabs Ltd.</span></p>
<p><span style="font-weight: 400;">9.5 Pound Cabs Ltd will do our best to resolve any disputes over these Terms. If you wish to take court proceedings against Pound Cabs Ltd you must do so within the UK. </span></p>
<p><span style="font-weight: 400;">9.6 These Terms are dated 30 January 2016</span></p>