<p><strong>Passenger Terms &amp; Conditions of Service</strong></p>
<p><strong>1 ABOUT ROADYO1.0 LTD TERMS AND CONDITIONS</strong></p>
<p><span style="font-weight: 400;">1.1 In these terms and conditions, as they may be amended from time to time ( &ldquo;Terms &amp; Conditions&rdquo; ) references to &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo; and any similar expression shall include the Company and (to the extent required where these terms are incorporated by reference in any other agreement) any subsidiary of the Company. Unless the context otherwise requires, words denoting the singular shall include the plural and vice versa, words denoting any gender shall include all genders and words denoting persons shall include bodies corporate and unincorporated, associations, partnerships and individuals. </span></p>
<p><span style="font-weight: 400;">These Terms &amp; Conditions are entered into between "us" "we" (&ldquo;Roadyo1.0 Ltd&rdquo;) and the customer or passenger (&ldquo;you&rdquo;).</span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<p><strong>2 INFORMATION ABOUT ROADYO1.0 LTD &nbsp;</strong></p>
<p><span style="font-weight: 400;">2.1 Roadyo1.0 Ltd is a marketing platform between BUSINESSES (taxi companies/private hire firms) and USERS (customers) linking the two together allowing users to access transport via Roadyo1.0 Ltd's affiliated BUSINESSES. Roadyo1.0 Ltd's company number 09403318, registered at </span><strong>&nbsp;</strong><span style="font-weight: 400;">HQ Hamill, Clippers Quay, Salford Quays, M50 3XP, UK</span></p>
<p><span style="font-weight: 400;">2.2 The registration and signup process for the passenger is free. &nbsp;Roadyo1.0 reserves the right to levy cancellation charges set out in section 4 of this document. &nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;">2.3 Roadyo1.0 Ltd will install Personal Digital Assistant (PDA) into each vehicle which enters into a contract with Roadyo1.0 Ltd. </span></p>
<p><span style="font-weight: 400;">2.4 When a passenger (you) makes a booking via the Roadyo1.0 Ltd APP the driver will be able to see the closest job. The driver will be presented with an option to accept the job by clicking &ldquo;yes&rdquo; on the PDA. &nbsp;Once the driver has accepted the job the driver is deemed as committed and bound to carry out the selected job. &nbsp;Roadyo1.0 Ltd reserves the right to exercise cancellation clauses listed in section 4 of this document. </span></p>
<p><span style="font-weight: 400;">2.5 The passenger (you) pays the full fare to the driver in cash or pay Roadyo1.0 Ltd direct via Roadyo1.0 Ltd's APP. </span></p>
<p><span style="font-weight: 400;">2.6 Our email is info@roadyo1.0.co.uk, (&ldquo;Roadyo1.0 Ltd&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; and &ldquo;our&rdquo;). For further details about Roadyo1.0 Ltd visit our website; </span><span style="font-weight: 400;">www.roadyo1.0.co.uk</span><span style="font-weight: 400;"> For information on how we will process your personal data, please see our Privacy Policy.</span></p>
<p><strong>3 YOUR USE OF ROADYO1.0 LTD'S SERVICES</strong></p>
<p><span style="font-weight: 400;">3.1 You can only use the Roadyo1.0 Ltd services (which include the Roadyo1.0 APP) if you have successfully completed your registration with us and that registration remains valid. Your registration remains at our discretion at all times. You will be deemed to have accepted these terms and conditions (&ldquo;Terms&rdquo;) when you register with us and whenever you use any of such Roadyo1.0 Ltd services.</span></p>
<p><span style="font-weight: 400;">3.2 By accessing and using the Website you the user ("you") are agreeing to be bound by these terms and conditions (the "Terms") which govern your access to and use of the Website.</span></p>
<p><span style="font-weight: 400;">3.3 Access to the site is permitted on a temporary basis and the Roadyo1.0 Ltd reserves the right to withdraw or amend the services provided on the site without notice. Roadyo1.0 Ltd will not be liable if for any reason the site is unavailable at any time or for any period.</span></p>
<p><span style="font-weight: 400;">3.4 Roadyo1.0 Ltd may restrict access to users to some parts of the site or to the entire site for technical, administrative or legal reasons.</span></p>
<p><span style="font-weight: 400;">3.5 If you choose, or you are provided with, a user identification code, password or any other piece of information as part of the Roadyo1.0 Ltd's security procedures, you must treat such information as confidential and you must not disclose it to any third party. Roadyo1.0 Ltd has the right to disable any identification code or password whether chosen by you or allocated by the Roadyo1.0 Ltd at any time if in the Roadyo1.0 Ltd'S opinion you have failed to comply with any of the provisions of these terms of use.</span></p>
<p><span style="font-weight: 400;">3.6 You are responsible for making all arrangements necessary for you to have access to the site. You are also responsible for ensuring that all persons who access the site through your internet connection are aware of these terms and that they comply with them.</span></p>
<p><span style="font-weight: 400;">3.7 You may use the site or APP only for lawful purposes. You must not use the site:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">In any way that breaches any applicable local, national or international law or regulation.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">In any way that is unlawful or fraudulent or has any unlawful or fraudulent purpose or effect.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">For the purpose of harming or attempting to harm minors in any way.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To send, knowingly receive, upload, download, use or re-use any material that does not comply with Content Standards.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To transmit or procure the sending of any unsolicited or unauthorised advertising or promotional material or any other form of similar solicitation (spam).</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To knowingly transmit any data, send or upload any material that contains viruses or any other computer code, programs or files designed to destroy, interrupt or limit the functionality of any computer, computer software or hardware or telecommunications equipment.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To provide false, inaccurate data. You can update or correct your details at any time via the Roadyo1.0 Ltd app.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To do anything which we reasonably believe to be disreputable or capable of damaging our reputation.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;"> To be in breach of confidence or privacy or of any third party&rsquo;s rights including copyright, trade mark or other intellectual property rights; (iii) is posted, shared or transmitted for the purpose of advertising or promoting yourself or any third party; or (iv) is misleading or misrepresentative as to your identity or which in any way suggests that you are sponsored, affiliated or connected with Roadyo1.0 Ltd.</span></li>
</ul>
<p><span style="font-weight: 400;">3.8 The use of Roadyo1.0 Ltd services grants you no rights in relation to our intellectual property rights (including, without limitation, copyright, trade marks, logos, graphics, photographs, animations, videos and text or rights in and to Roadyo1.0 Ltd's software, applications and website) or the intellectual property of our retail or advertising partners, other than the non&shy;transferable, personal right to use and receive the Roadyo1.0 Ltd services in accordance with Roadyo1.0 Ltd's Terms.</span></p>
<p><span style="font-weight: 400;">3.9 and warrant that when using any Roadyo1.0 Ltd services: you have all the appropriate licenses, approvals and authority to provide taxi services to passengers; that you own or have the legal right to operate the vehicle you use and that such vehicle meets all relevant safety standards and regulatory requirements and laws; and that you have valid insurance cover for your vehicle and services.</span></p>
<p><span style="font-weight: 400;">3.10 and acknowledge that we have limited control over the nature and content of information and chat transmitted or received by you or other users of any Roadyo1.0 Ltd services. Although we reserve the right to do so, we do not monitor such content in the usual course of business and will not be liable for any such content. If you have a complaint about another user please contact us via the Roadyo1.0 Ltd app or visit our website; </span><span style="font-weight: 400;">info@roadyo1.0.co.uk</span><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">3.11 to compensate and defend us fully against any claims or legal proceedings brought against us by any other person as a result of your breach of these Terms.</span></p>
<p><span style="font-weight: 400;">3.12 that you will comply with all applicable laws and requirements in force from time to time and be ultimately responsible for the provision of your taxi services to passengers (including without limitation, following safety laws in for the use of mobile devices while driving).</span></p>
<p><span style="font-weight: 400;">3.13 In relation to the reporting information that we provide, we use all reasonable endeavours to ensure that such information is reasonably accurate but we cannot provide guarantee that it will always be correct or accurate . You should use your own judgment when acting on the basis of information provided.</span></p>
<p><span style="font-weight: 400;">3.14 Roadyo1.0 Ltd APP is a Roadyo1.0 Ltd service to arrange payments from passengers whether or not they have booked a taxi using the Roadyo1.0 Ltd app.</span></p>
<p><span style="font-weight: 400;">3.15 Roadyo1.0 Ltd are not responsible for the behaviour, actions or inactions of passengers whether or not they are Roadyo1.0 Ltd customers (although, where such passenger is a Roadyo1.0 Ltd customer who has ordered your taxi using the Roadyo1.0 Ltd APP , payment protection is provided in certain circumstances. Any contract for the provision of taxi services is between you and the passenger and not Roadyo1.0 Ltd. &nbsp;Roadyo1.0 Ltd simply provide a portal to introduce drivers and passengers and/or facilitate payments in certain circumstances.</span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<ol start="4">
<li><strong> CHARGES AND PAYMENT</strong></li>
</ol>
<p><span style="font-weight: 400;">4.1 You can obtain full details about the cost of taxi journeys with Roadyo1.0 by visiting our website; </span><a href="http://www.cabtransfers.co.uk"><span style="font-weight: 400;">www.cabtransfers.co.uk</span></a><span style="font-weight: 400;"> For certain services Roadyo1.0 Ltd may also charge you a commission or service charge as detailed in that Roadyo1.0 Ltd service;</span></p>
<p><span style="font-weight: 400;">4.2 Roadyo1.0 Ltd will charge you after the end of the journey using the payment details you have provided Roadyo1.0 Ltd when using Roadyo1.0 Ltd services including the APP. </span></p>
<p><span style="font-weight: 400;">4.3 Roadyo1.0 Ltd reserves the right to carry out authorisation checks on any payment details that you have provided Roadyo1.0 Ltd (including credit and debit cards) at any time. Roadyo1.0 Ltd will store any payment details you have provided to so they may be used for payments you need to make whenever you use the Roadyo1.0 Ltd services including APP at any time and/or to collect any money you may owe &nbsp;Roadyo1.0 Ltd. Please see Roadyo1.0 Ltd's privacy policy </span><span style="font-weight: 400;">here</span><span style="font-weight: 400;"> on how we will use, protect and store your personal data.</span></p>
<p><span style="font-weight: 400;">4.4 During the registration process of the Roadyo1.0 Ltd APP you will be presented with an option to pre-set a default "tip" percentage. &nbsp;At the end of the journey this amount will automatically be added to the taxi fee unless you override it with a different tip amount or you choose to remove the tip amount. </span></p>
<p><span style="font-weight: 400;">4.5 You may not be able to cancel once you have commenced a taxi journey or made a payment in advance of your taxi journey as the service has deemed to have been provided. &nbsp;Roadyo1.0 Ltd will take your payment automatically which is non&shy;refundable. If you have any complaint in relation to the taxi service provided then that dispute must be taken up with the taxi driver directly. If you are unable to resolve the dispute with the taxi driver or you cannot come to an agreement with the taxi driver, please contact Roadyo1.0 Ltd and we will try to resolve the dispute.</span></p>
<p><span style="font-weight: 400;">4.5 You will also agree to pay any additional charges where taxis have been organised via Roadyo1.0 Ltd services (for example where you then do not complete that journey or cancel an order when a taxi has already been allocated to you or for any damage or cleaning costs to the taxi which you incur) as set out in more detail here:</span></p>
<p><span style="font-weight: 400;">Cancellation: We may charge a &pound;5 cancellation fee if you cancel an order after a taxi has been allocated to your job. </span></p>
<p><span style="font-weight: 400;">Cleaning: You will be charged &pound;50 if after your journey the taxi requires cleaning.</span></p>
<p><span style="font-weight: 400;">Damage: You will be charged at cost for any damage to the taxi caused by you. &nbsp;We may also refer you to the Police for prosecution where it is deemed necessary for example in case of criminal damage. </span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<ol start="5">
<li><strong> TERMINATION</strong></li>
</ol>
<p><span style="font-weight: 400;">5.1 We may terminate these Terms and close any account you have with us by giving you 7 days' notice in writing by email to your registered email address. We may also terminate these Terms and close your account without notice if you breach any of your obligations under these Terms, if you cease to be a licensed taxi driver, if bankruptcy proceedings are brought against you or if you do not pay a court judgement on time.</span></p>
<p><span style="font-weight: 400;">5.2 We reserve the right to suspend, restrict or terminate your access to Roadyo1.0 Ltd at any time without notice if we have reasonable grounds to believe you have breached any of these Terms. This shall not limit our right to take any other action against you that we consider appropriate to defend our rights or those of any other person.</span></p>
<p><span style="font-weight: 400;">5.3 You may cancel these Terms at any time by simply closing your account by following the instructions on the APP or website.</span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<ol start="6">
<li><strong> ROADYO1.0'S LEGAL OBLIGATIONS AND LIMITS ON LIABILITY</strong></li>
</ol>
<p><span style="font-weight: 400;">6.1 Roadyo1.0 Ltd accept liability for death or personal injury caused by our negligence or that of our employees and agents. We do not seek to exclude liability for fraudulent misrepresentation by us or our employees or agents. You have certain rights under the law. These include that we will provide Roadyo1.0 Ltd to a reasonable standard and within a reasonable time. Your statutory rights remain unaffected. For more information about your statutory rights you can contact your local Citizens Advice Bureau, Trading Standards Office or consult a legal representative.</span></p>
<ol start="7">
<li><strong> LIMITS ON LIABILITY </strong></li>
</ol>
<p><span style="font-weight: 400;">7.1 If Roadyo1.0 Ltd is in breach of these Terms, We shall only be liable for losses which are a reasonably foreseeable consequence of such a breach, up to a maximum of &pound;1,000. "Foreseeable" means that the losses could have been reasonably contemplated by you and us at the time of entering into these Terms.</span></p>
<p><span style="font-weight: 400;">7.2 Roadyo1.0 Ltd is not responsible for: (i) losses not caused by our breach; (ii) the actions or inactions of any passengers (other than in the circumstances set out in clause 2.2); (iii) the actions or inactions of other drivers; (iv) indirect losses which means loss to you which is a side effect of the main loss or damage and where you and us could not have reasonably anticipated that type of loss arising at the time of entering into these Terms; or (v) failure to provide Taxi-e Ltd or to meet any of our obligations under these Terms where such failure is due to events beyond our control (for example a network failure).</span></p>
<p><strong><strong>&nbsp;</strong></strong></p>
<ol start="8">
<li><strong> PROMOTIONS</strong></li>
</ol>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">These Promotion general terms and conditions apply to each and every Promotion.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">In addition, all instructions, rules and conditions relating to a specific Promotion form part of these general Promotion terms and conditions but in the event of conflict these provisions shall prevail.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Roadyo1.0 Ltd reserves the right to change the terms and conditions of its Promotions (and any Standard Roadyo1.0 Ltd Terms and Conditions) at its discretion.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">A Promotion is an entitlement to a Discount (up to the amount stated) off a qualifying booking.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">A Promotion is only valid on the Roadyo1.0 Ltd website and the APP for a qualifying booking.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">A Promotion is subject to availability and is not an indication of availability. In particular, Roadyo1.0 Ltd reserves the right to cancel a Promotion and/or to reject redemption of a Promotional Code when the total value of the Promotional Codes already redeemed exceeds a certain financial value.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">A Promotion is not an entitlement to make a specific booking or to travel on a specific date or via a specific route.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Roadyo1.0 Ltd reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that Roadyo1.0 Ltd determines or believes that the use or redemption of the Promotional Code was in error, fraudulent, illegal, or in violation of the applicable Promotional Code terms or these Terms.</span></li>
</ul>
<ol start="9">
<li><strong> COMPETITIONS RULES</strong></li>
</ol>
<p><span style="font-weight: 400;">9.1 Roadyo1.0 Ltd requires you to refer to its full Competition Rules page before entering into any Roadyo1.0 Ltd competition. Roadyo1.0 Ltd posts the details of all competitions on Roadyo1.0 Ltd'a web site where the closing date is specified. To enter any Roadyo1.0 Ltd competition you must be: (a) united kingdom resident; and (b) 18 years old or over at the time of entry. No purchases are necessary. Any employees or members of immediate family of Roadyo1.0 Ltd are restricted from entering any Competitions. </span></p>
<ol start="10">
<li><strong> SUBCONTRACTING, SERVICE LEVELS &amp; DISPUTE RESOLUTION</strong></li>
</ol>
<p><span style="font-weight: 400;">10.1 Roadyo1.0 Ltd may wish to transfer its rights or obligations or sub-contract its obligations under these Terms to another legal entity. You agree that Roadyo1.0 Ltd may do so provided that this will not adversely affect the standard of service you receive under these Terms. As set out in clause 5.3, you may terminate your agreement with Roadyo1.0 Ltd at any time. These Terms are personal to you. You may not transfer your rights or obligations under these Terms to anyone else.</span></p>
<p><span style="font-weight: 400;">10.2 If you are in breach of Roadyo1.0 Ltd's Terms and Roadyo1.0 Ltd takes no action against you, Roadyo1.0 Ltd will still be entitled to its rights and remedies in any other situation where you breach these Terms.</span></p>
<p><span style="font-weight: 400;">10.3 If any part of these Terms is disallowed or found to be ineffective by any court or regulator, the other provisions shall continue to apply.</span></p>
<p><span style="font-weight: 400;">10.4 These Terms are not intended to give rights to anyone except you and Roadyo1.0 Ltd.</span></p>
<p><span style="font-weight: 400;">10.5 Roadyo1.0 Ltd will do its best to resolve any disputes over these Terms. If you wish to take court proceedings against Roadyo1.0 Ltd you must do so within the UK jurisdiction. </span></p>
<p><span style="font-weight: 400;">10.6 These Terms are dated 30 January 2016</span></p>
<p><span style="font-weight: 400;">.</span></p>